# Generated by Django 5.2.5 on 2025-09-29 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=10)),
                ('About', models.TextField()),
                ('Position', models.CharField(choices=[('manager', 'manager'), ('software developer', 'sd'), ('project lead', 'pl')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
